ruby/1.9: change base image to a more modern one.
Using original official image, unfortunately, fails starting with containerd 2.0 with the error:

```
ERROR: failed to build: failed to solve: Pulling Schema 1 images have been deprecated and disabled by default since containerd v2.0. As a workaround you may set an environment variable `CONTAINERD_ENABLE_DEPRECATED_PULL_SCHEMA_1_IMAGE=1`, but this will be completely removed in containerd v2.1.
```

Instead of working this around, we will just use a fresher third-party base image.